totall friggin rewrite

diff --git a/aaa-build-scripts-001/aaa-test b/aaa-build-scripts-001/aaa-test
--- a/aaa-build-scripts-001/aaa-test
+++ b/aaa-build-scripts-001/aaa-test
@@ -1,789 +1,173 @@
 #!/bin/bash
 
+################ common header identical except for usage, getopts etc #########################################################################################################
 
-echo '#!/bin/bash
-unset pkgname depends makedepends optdepends
-. "$1/PKGBUILD"
-for dep in "${depends[@]}"; do
-	# lose the version comparator, if any
-	depname=${dep%%[<>=]*} && echo "$depname"
-done
-for dep in "${makedepends[@]}"; do
-	# lose the version comparator, if any
-	depname=${dep%%[<>=]*} && echo "$depname"
-done
-if [[ $2 == "--opt" ]]; then
-	for dep in "${optdepends[@]/:*}"; do
-		# lose the version comaparator, if any
-		depname=${dep%%[<>=]*} && echo "$depname"
-	done
+
+Usage() {
+  cat <<EOF
+usage: ${0##*/} [options] </path/to/pkg/dir.../path/to/pkg/dir>
+
+  -d < distro >
+  -d <backport build to selected distro
+	kali|stable|testing
+	default build is unstable>
+  
+  -q <supress normal output, just print
+  names of files sucsessfully built and 
+  processed>
+  
+  -u <update/create pbuilder immage before
+   build>
+   
+   -c <just check the package for packaging
+   correcly ie dpkg-source -b implies no quiet>
+   
+   -G <git build ie include to git component>
+   
+  ****repo flags*****
+  -l < include built .changes to home repo,
+	basedir=aaa_home_repo_dir
+	distro=aaa_debian_distro
+	only effective if repo dir set in
+	aaa-master-config
+	
+  -g <also include packages into git repo>
+	basedir=aaa_git_repo_dir
+	distro=aaa_debian_distro
+	only effective if repo dir set in
+	aaa-master-config
+  
+  -w <also include packages into work repo>
+	basedir=aaa_work_repo_dir
+	distro=work
+	only effective if repo dir set in
+	aaa-master-config
+  
+  aaa_debian_distro
+	sourced from /etc/aaa-master-config
+	<aaa_debian_distro> overwrtten by -d
+	< distro > >
+   
+  This script uses pbuilder and reprepro
+  to build the package in the current dir
+  result is found at the location
+  specified in aaa-master-configure
+  as aaa_build_result
+  
+
+EOF
+}
+
+
+
+if [[ $1 = @(-h|--help) ]]; then
+  Usage
+  exit 1
 fi
-exit 0' > "$HOME/work/axe_get_deps"
 
-echo '#!/bin/bash
-unset pkgname pkgver _arch_rel _axe_rel pkgrel pkgbase _axe_native_rel
-. "$1/PKGBUILD"
-
-if [[ $pkgbase ]];then
-	echo "$pkgbase"
+#source common functions
+if [[ -r /usr/bin/aaa-common-functions ]]; then
+	. /usr/bin/aaa-common-functions
+	if [[ ! $? -eq 0 ]]; then
+		echo " failed to source common functions at /usr/bin/aaa-common-functions"
+		echo "quitting !! "
+		exit 1
+	fi
 else
-	if [[ $pkgname ]];then
-		echo "$pkgname"
+	echo " failed to find common functions at /usr/bin/aaa-common-functions"
+	echo "quitting !! "
+	exit 1
+fi
+
+#source config
+if [ -r /etc/aaa-master-config ]; then
+  Info "found my master config file.. reading it"
+  . /etc/aaa-master-config
+	if [ -r $HOME/.aaa-local-config ]; then
+		Info "found a local settings file.. reading it"
+		. $HOME/.aaa-local-config
+	fi
+else
+	Fuck "Failed to find master config file quitting"
+	exit 1
+fi
+
+#source settings
+if [ -r $HOME/.aaa_settings ]; then
+  Info "found a settings file.. reading it"
+  . $HOME/.aaa_settings
+fi
+
+####
+aaa_component="main"
+
+# get options and arguments http://wiki.bash-hackers.org/howto/getopts_tutorial
+
+while getopts ":d:uqlgwcG" opt; do
+  case $opt in
+        d) Info "< -d $OPTARG > passed" 
+		case $OPTARG in
+	kali|stable|testing) Info "-d $OPTARG is valid, building backport for $OPTARG"
+							new_distro="$OPTARG" ;;
+					*) Fuck "<-d $OPTARG> is not valid, needs to be <-d kali,stable,unstable,testing or ubuntu>" ;;
+		esac ;;
+	u) update=1 ;;
+	q) quiet=1 ;;
+	l) if [[ -z  "$aaa_home_repo_dir" ]]; then
+			Warn "/etc/aaa-master-config has no reference for aaa_home_repo_dir"
+			Warn "if you continue your home repo will not be used "
+			AnyKey
+		else
+			add_to_home_repo=1
+		fi ;;
+	g) if [[ -z  "$aaa_git_repo_dir" ]]; then
+			Warn "/etc/aaa-master-config has no reference for aaa_git_repo_dir"
+			Warn "if you continue your home repo will not be used "
+			AnyKey
+		else
+			add_to_git_repo=1
+		fi ;;
+	w) if [[ -z  "$aaa_work_repo_dir" ]]; then
+			Warn "/etc/aaa-master-config has no reference for aaa_work_repo_dir"
+			Warn "if you continue your work repo will not be used "
+			AnyKey
+		else
+			add_to_work_repo=1
+		fi ;;
+	c) check=1 
+		quiet=0;;
+	G) git_build=1 ;;
+   \?) Fuck "Invalid option: -$OPTARG" ;;
+    :) Fuck "Option -$OPTARG requires a distro name, kali,stable,unstable,testing or ubuntu" ;;
+  esac
+done
+
+#sort vars
+
+
+if [[ $git_build -eq 1 ]]; then 
+	if [[ $new_distro ]]; then
+		SwitchDistro "$new_distro"
+		aaa_component="$aaa_debian_distro"git
 	else
-		echo "null"
+		aaa_component="$aaa_default_distro"git
+	fi
+else
+	if [[ $new_distro ]]; then
+		SwitchDistro "$new_distro"
+		aaa_component="$aaa_debian_distro"
+	else
+		aaa_component="unstable"
+		rm -f "$HOME/.pbuilderrc"
 	fi
 fi
+#shift the options and args out the way http://wiki.bash-hackers.org/howto/getopts_tutorial
+shift $((OPTIND-1))
+#and lets parse it
 
-if [[ $pkgver ]];then
-	echo "$pkgver"
-else
-	echo "null"
-fi
+AutoIncludeHome
+AutoIncludeWork
+AutoIncludeGit
 
-if [[ $pkgrel ]];then
-	echo "$pkgrel"
-else
-	echo "null"
-fi
-
-if [[ $_arch_rel ]];then
-	echo "$_arch_rel"
-else
-	echo "null"
-fi
-
-if [[ $_axe_rel ]];then
-	echo "$_axe_rel"
-else
-	if [[ $_axe_native_rel ]];then
-		echo "$_axe_native_rel"
-	else
-		echo "null"
-	fi
-fi
-
-if [[ $_axe_native_rel ]];then
-	echo "axis"
-else
-	echo "archlinux"
-fi
-
-if [[ $pkgbase ]];then
-	echo "split"
-else
-	echo "single"
-fi
-
-exit 0
-' > "$HOME/work/axe_get_vers"
-
-
-
-echo "linux-api-headers
-glibc
-binutils$_AXE_MULTILIB_SUFFIX
-gcc$_AXE_MULTILIB_SUFFIX
-libtool$_AXE_MULTILIB_SUFFIX
-zlib
-file
-gmp
-mpfr
-libmpc
-attr
-acl
-isl
-cloog
-glpk
-ppl" > "$HOME/work/toolchain.list"
-
-#list good as of 1/12/2012
-echo "#base system packages, order from LFS mainly REMEMBER THERE MUST BE A SPACE BETWEEN ENTRIES
-sed 
-bzip2 
-ncurses 
-dialog 
-shadow 
-libcap 
-coreutils 
-bash 
-m4 
-bison 
-procps-ng 
-grep 
-readline 
-gdbm 
-inetutils 
-db 
-perl 
-autoconf 
-automake 
-procinfo-ng 
-diffutils 
-gawk 
-findutils 
-flex 
-gettext 
-groff 
-xz 
-less 
-gzip 
-iproute2 
-kbd 
-kmod 
-make 
-libpipeline 
-man-db 
-patch 
-tar 
-texinfo 
-dash 
-fakeroot 
-elfutils 
-# the rest of the base packages including udev deps
-libsigc++ 
-glibmm 
-eventlog 
-expat 
-perl-xml-parser 
-intltool 
-libgssglue 
-libtirpc 
-cracklib 
-valgrind 
-hdparm 
-idnkit 
-ifenslave 
-iptables 
-libcap-ng 
-keyutils 
-libedit 
-libnl 
-libusbx 
-libusb-compat 
-lzo2 
-net-tools 
-run-parts 
-popt 
-sysfsutils 
-traceroute 
-p11-kit 
-nettle 
-libtasn1 
-gnutls 
-usbutils 
-libpcap 
-freetype2 
-fontconfig 
-nano 
-bridge-utils 
-wireless_tools 
-which 
-psmisc 
-pambase 
-pam 
-util-linux 
-e2fsprogs 
-mlocate 
-isdn4k-utils 
-ifenslave 
-pth 
-pcre 
-libffi 
-openssl 
-glib2 
-pkg-config 
-desktop-file-utils 
-pinentry 
-isdn4k-utils 
-libarchive 
-iputils 
-libsasl 
-openldap 
-libssh2 
-curl 
-openslp 
-dnsutils 
-mtdev 
-acpid 
-xf86-input-evdev 
-mkinitcpio-nfs-utils 
-mkinitcpio-busybox 
-mkinitcpio 
-udev-axe 
-syslog-ng 
-dbus 
-lvm2 
-dmraid 
-libwacom 
-iw 
-libatasmart 
-lockdev 
-libgpg-error 
-libassuan 
-libgcrypt 
-libsecret 
-libxslt 
-libksba 
-sdparm 
-libgusb 
-crda 
-cronie 
-dnsmasq 
-dhcpcd 
-dhcp 
-gpm 
-krb5 
-heirloom-mailx 
-mdadm 
-netcfg 
-librpcsecgss 
-dirmngr 
-nfsidmap 
-rpcbind 
-openssh 
-openvpn 
-pciutils 
-pcmciautils 
-openmpi 
-boost 
-gnupg 
-gpgme 
-ppp 
-rfkill 
-cryptsetup 
-logrotate 
-wpa_supplicant 
-#sudo 
-nfs-utils 
-sysvinit 
-wpa_actiond 
-# the extended components leading to a desktop eventually
-menu-cache 
-sqlite 
-python2 
-python 
-pygobject2 
-pygobject
-p11-kit 
-nettle 
-libtasn1 
-gnutls 
-libxml2 
-libpng 
-netpbm 
-libice 
-libsm 
-libxt 
-libxdmcp 
-libxau 
-libxcb 
-xcb-util 
-startup-notification 
-pmount 
-libx11 
-libxv 
-libxext 
-libdmx 
-libxi 
-libxt 
-libxss 
-libxmu 
-libxrender 
-libxfixes 
-libxcursor 
-libfs 
-libxft 
-libxrandr 
-libxinerama 
-libxcomposite 
-libxpm 
-libxtst 
-libfontenc 
-libxfont 
-xorg-xkbcomp 
-libxkbfile 
-libxklavier 
-links 
-orc 
-libogg 
-libvorbis 
-cdparanoia 
-shared-mime-info 
-jade 
-docbook-xml 
-rarian 
-gnome-doc-utils 
-gtk-doc 
-pixman 
-flac 
-libsndfile 
-libsamplerate 
-libxxf86vm 
-cairo 
-python2-cairo 
-hwloc 
-libdatrie 
-libthai 
-pango 
-gstreamer0.10 
-gstreamer0.10-base 
-gstreamer0.10-good 
-bluez 
-python2-pybluez 
-libpciaccess 
-libdrm 
-mesa 
-libwnck3 
-freeglut 
-libjpeg-turbo 
-libtiff 
-lcms2 
-alsa-lib 
-alsa-utils 
-alsa-firmware 
-alsa-plugins 
-python2-pyalsa 
-python-pyalsaaudio 
-jasper 
-lcms 
-pyudev 
-rsync 
-vala 
-libfm 
-spacefm 
-libplist 
-usbmuxd 
-libxvmc 
-xinetd 
-xorg-server 
-xf86-video-nouveau 
-xf86-video-intel 
-xorg-xrandr 
-xorg-xbacklight 
-xorg-xauth 
-xorg-xinit 
-xorg-utils 
-xorg-server-utils 
-xf86-input-synaptics 
-numactl 
-icu 
-libfbclient 
-irqbalance 
-dkms 
-distcc 
-bftpd 
-connman 
-atop 
-arptables 
-audit 
-libdaemon 
-libexif 
-libgdiplus 
-mono 
-bc 
-nss-mdns 
-libglade 
-python2-cairo 
-lapack 
-python-nose 
-python-numpy 
-pygtk 
-dbus-glib 
-dbus-python 
-vte3 
-libmng 
-mysql 
-postgresql 
-unixodbc 
-atk 
-gdk-pixbuf2 
-libnotify 
-python-notify 
-cups 
-libexif 
-apcupsd 
-system-config-printer 
-pycups 
-talloc 
-cifs-utils 
-samba 
-pysmbc 
-sane 
-colord 
-gtk 
-gtk2 
-gtk3 
-gtk3-axe 
-avahi 
-libcroco 
-librsvg 
-emacs 
-apr-util 
-apache 
-git 
-subversion 
-texlive-bin 
-qt3 
-tcl 
-tk 
-avahi 
-ghostscript 
-doxygen 
-man-db 
-groff 
-libasyncns 
-fftw 
-pulseaudio 
-parted 
-sg3_utils 
-lsof 
-gptfdisk 
-fuse 
-laptop-mode-tools 
-networkmanager 
-modemmanager 
-network-manager-applet 
-libvirt 
-eeze 
-pup-volume-monitor " > "$HOME/work/axe.list"
-
-
-	
-echo "nvclock --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-nvdock --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-libvdpau --install --con $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-libcl --install --con $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-nvidia-utils --install --con $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-nvidia --install --con $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-cuda --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-nvidia-cg-toolkit --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-#pycuda out of date in arch and not compiling, waiting for arch to sort it out
-#python2-pycuda --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck" > "$HOME/work/nvidia.list"
-
-	
-echo "nspr 
-js 
-exempi 
-python-lxml 
-gnome-python 
-python-markupsafe 
-python2-imaging 
-gobject-introspection 
-polkit-axe 
-perl-yaml-syck 
-xmlto 
-consolekit --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-polkit-gnome 
-accountsservice --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-dconf 
-libgnomekbd 
-at-spi2-core 
-at-spi2-atk 
-cogl 
-json-glib 
-clutter 
-libgee 
-caribou 
-dbus-glib 
-gjs 
-libcddb 
-libcdio 
-libgnome-keyring 
-gnome-keyring 
-upower 
-libgtop 
-libpwquality 
-libproxy 
-glib-networking 
-libsoup 
-udisks 
-udisks2 
-gvfs 
-obexd 
-gnome-bluetooth 
-gnome-desktop 
-gnome-menus 
-gnome-menus2 
-tdb 
-gconf --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-libgksu 
-gksu 
-libcanberra --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-notification-daemon 
-gnome-terminal 
-telepathy-glib 
-gnome-panel --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-gnome-settings-daemon --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-muffin-wm --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-muffin-git 
-#telepathy-logger 
-gnome-control-center --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-gnome-session --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-cinnamon 
-#cinnamon-git 
-nemo-fm 
-nemo-git 
-pup-volume-monitor 
-alacarte 
-connman-gnome-git 
-xfce4-session 
-gparted 
-packagekit 
-zenity 
-metacity 
-compiz-ubuntu --install-force --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck" > "$HOME/work/desktop.list"
-
-echo "syslog-ng --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-mkinitcpio --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-dbus --install --con $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-udev-axe --install --con $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag $_AXE_GLOBAL_CHECK
-pcmciautils --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag $_AXE_GLOBAL_CHECK
-crda --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag $_AXE_GLOBAL_CHECK
-libgusb --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag $_AXE_GLOBAL_CHECK
-pyudev --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag $_AXE_GLOBAL_CHECK
-libatasmart --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag $_AXE_GLOBAL_CHECK
-lockdev --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag $_AXE_GLOBAL_CHECK
-#known arch fail, willnot be back in list till i fix it
-#libcec --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag $_AXE_GLOBAL_CHECK
-syslog-ng --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --notag $_AXE_GLOBAL_CHECK
-mkinitcpio-busybox --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --notag $_AXE_GLOBAL_CHECK
-mkinitcpio --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --notag $_AXE_GLOBAL_CHECK
-dbus --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --notag $_AXE_GLOBAL_CHECK
-lvm2 --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag $_AXE_GLOBAL_CHECK
-dmraid --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag $_AXE_GLOBAL_CHECK
-mtdev --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag $_AXE_GLOBAL_CHECK
-xf86-input-evdev --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag $_AXE_GLOBAL_CHECK
-xorg-server --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag $_AXE_GLOBAL_CHECK
-xf86-video-nouveau --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag $_AXE_GLOBAL_CHECK
-xf86-video-intel --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag $_AXE_GLOBAL_CHECK
-xf86-video-modesetting --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag $_AXE_GLOBAL_CHECK
-polkit-axe --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-consolekit --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag $_AXE_GLOBAL_CHECK
-cronie --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag $_AXE_GLOBAL_CHECK
-libwacom --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-colord --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-cups --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-system-config-printer --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-gstreamer0.10-good --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-bluez --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-mesa --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-mysql --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-udisks --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-udisks2 --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-pulseaudio --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-upower --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-gvfs --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-libvirt --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-eeze --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --tag --nocheck
-networkmanager --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --notag $_AXE_GLOBAL_CHECK
-modemmanager --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --notag $_AXE_GLOBAL_CHECK
-packagekit --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --notag --nocheck
-pup-volume-monitor --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --notag --nocheck
-thunar --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --notag $_AXE_GLOBAL_CHECK
-udevil --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --notag $_AXE_GLOBAL_CHECK
-spacefm --install --nocon $_AXE_PKGBUILD_DIR $_AXE_OPT_TYPE --nofail --nosuc --notag $_AXE_GLOBAL_CHECK" > "$HOME/work/replace_systemd.list"
-
-
-echo "syslog-ng
-mkinitcpio
-dbus
-udev-axe
-pcmciautils
-crda
-libgusb
-pyudev
-libatasmart
-lockdev
-#known arch fail, willnot
-#libcec
-syslog-ng
-mkinitcpio-busybox
-mkinitcpio
-dbus
-lvm2
-dmraid
-mtdev
-xf86-input-evdev
-xorg-server
-xf86-video-nouveau
-xf86-video-intel
-xf86-video-modesetting
-polkit-axe
-consolekit
-cronie
-libwacom
-colord
-cups
-system-config-printer
-gstreamer0.10-good
-bluez
-mesa
-mysql
-udisks
-udisks2
-pulseaudio
-upower
-gvfs
-libvirt
-eeze
-networkmanager
-modemmanager
-packagekit
-pup-volume-monitor
-thunar
-udevil
-spacefm" > "$HOME/work/x64.list"
-
-
-echo "acl
-acpi
-acpid
-apr
-apr-util
-attr
-autoconf
-automake
-bash
-bison
-bzip2
-ca-certificates
-cloog
-coreutils
-cracklib
-cronie
-cryptsetup
-curl
-db
-dbus
-device-mapper
-dhcpcd
-diffutils
-dirmngr
-e2fsprogs
-elfutils
-eventlog
-expac
-expat
-fakeroot
-file
-filesystem
-findutils
-flex
-freetype2
-fuse
-gawk
-gcc
-gcc-libs
-gdbm
-gettext
-git
-glib2
-glibc
-gmp
-gnupg
-gpgme
-gpm
-grep
-groff
-gzip
-heirloom-mailx
-hwids
-iana-etc
-inetutils
-iproute2
-iputils
-isl
-jfsutils
-kbd
-keyutils
-kmod
-krb5
-ldns
-less
-libarchive
-libassuan
-libcap
-libedit
-libffi
-libgcrypt
-libgpg-error
-libgssglue
-libksba
-libldap
-libltdl
-libmpc
-libnl
-libpcap
-libpipeline
-libsasl
-libssh2
-libtirpc
-libtool
-libusbx
-linux
-linux-firmware
-logrotate
-lvm2
-m4
-make
-man-db
-man-pages
-mc
-mdadm
-mkinitcpio
-mkinitcpio-busybox
-mpfr
-namcap
-nano
-ncurses
-neon
-openssh
-openssl
-package-query
-pacman
-pam
-pambase
-patch
-pciutils
-pcmciautils
-pcre
-perl
-perl-error
-pinentry
-pkg-config
-popt
-ppl
-ppp
-procps-ng
-psmisc
-pth
-pyalpm
-python
-python-pyelftools
-readline
-reiserfsprogs
-rsync
-run-parts
-sed
-shadow
-slang
-sqlite
-subversion
-sysfsutils
-syslog-ng
-sysvinit
-sysvinit-tools
-tar
-texinfo
-tzdata
-unixodbc
-usbutils
-util-linux
-vi
-which
-wpa_supplicant
-xfsprogs
-xz
-zlib" > "$HOME/work/base_reinstall.list"
 
 
